package com.gigaworks.tech.bloodbank.util

// Tag for logs
const val TAG = "BloodBank:DEBUG"

// OTP timer in seconds
const val OTP_TIMER = 120L

// Maharashtra cities list *will be removed after a while as this will be fetched via an API
val CITIES_LIST = listOf(
    "Ahmednagar",
    "Akola",
    "Akot",
    "Amalner",
    "Ambejogai",
    "Amravati",
    "Anjangaon",
    "Arvi",
    "Aurangabad",
    "Bhiwandi",
    "Dhule",
    "Kalyan-Dombivali",
    "Ichalkaranji",
    "Kalyan-Dombivali",
    "Karjat",
    "Latur",
    "Loha",
    "Lonar",
    "Lonavla",
    "Mahad",
    "Malegaon",
    "Malkapur",
    "Mangalvedhe",
    "Mangrulpir",
    "Manjlegaon",
    "Manmad",
    "Manwath",
    "Mehkar",
    "Mhaswad",
    "Mira-Bhayandar",
    "Morshi",
    "Mukhed",
    "Mul",
    "Greater Mumbai*",
    "Murtijapur",
    "Nagpur",
    "Nanded-Waghala",
    "Nandgaon",
    "Nandura",
    "Nandurbar",
    "Narkhed",
    "Nashik",
    "Navi Mumbai",
    "Nawapur",
    "Nilanga",
    "Osmanabad",
    "Ozar",
    "Pachora",
    "Paithan",
    "Palghar",
    "Pandharkaoda",
    "Pandharpur",
    "Panvel",
    "Parbhani",
    "Parli",
    "Partur",
    "Pathardi",
    "Pathri",
    "Patur",
    "Pauni",
    "Pen",
    "Phaltan",
    "Pulgaon",
    "Pune",
    "Purna",
    "Pusad",
    "Rahuri",
    "Rajura",
    "Ramtek",
    "Ratnagiri",
    "Raver",
    "Risod",
    "Sailu",
    "Sangamner",
    "Sangli",
    "Sangole",
    "Sasvad",
    "Satana",
    "Satara",
    "Savner",
    "Sawantwadi",
    "Shahade",
    "Shegaon",
    "Shendurjana",
    "Shirdi",
    "Shirpur-Warwade",
    "Shirur",
    "Shrigonda",
    "Shrirampur",
    "Sillod",
    "Sinnar",
    "Solapur",
    "Soyagaon",
    "Talegaon Dabhade",
    "Talode",
    "Tasgaon",
    "Thane",
    "Tirora",
    "Tuljapur",
    "Tumsar",
    "Uchgaon",
    "Udgir",
    "Umarga",
    "Umarkhed",
    "Umred",
    "Uran",
    "Uran Islampur",
    "Vadgaon Kasba",
    "Vaijapur",
    "Vasai-Virar",
    "Vita",
    "Wadgaon Road",
    "Wai",
    "Wani",
    "Wardha",
    "Warora",
    "Warud",
    "Washim",
    "Yavatmal",
    "Yawal",
    "Yevla"
)